# Generated by Django 5.1.5 on 2025-02-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formbuilder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="condition_trigger",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="hidden_questions",
            field=models.ManyToManyField(blank=True, to="formbuilder.question"),
        ),
    ]
