# Generated by Django 5.1.5 on 2025-02-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formbuilder", "0002_question_condition_trigger_question_hidden_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="condition_trigger",
        ),
        migrations.RemoveField(
            model_name="question",
            name="hidden_questions",
        ),
        migrations.AddField(
            model_name="question",
            name="main_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hidden_questions",
                to="formbuilder.question",
            ),
        ),
    ]
