# Generated by Django 5.1.5 on 2025-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formbuilder", "0003_remove_question_condition_trigger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="conditional_option",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
