# Generated by Django 5.1.5 on 2025-02-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formbuilder", "0005_alter_question_answer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("text", "Short Answer"),
                    ("textarea", "Paragraph"),
                    ("radio", "Multiple Choice (Radio)"),
                    ("checkbox", "Checkboxes"),
                    ("integer", "Integer"),
                ],
                max_length=20,
            ),
        ),
    ]
