# Generated by Django 5.1.5 on 2025-02-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formbuilder", "0006_alter_question_answer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="calculation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sum", "Total"),
                    ("average", "Average"),
                    ("percentage", "Percentage"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("text", "Short Answer"),
                    ("textarea", "Paragraph"),
                    ("radio", "Multiple Choice (Radio)"),
                    ("checkbox", "Checkboxes"),
                    ("integer", "Integer"),
                    ("calculated", "Calculated Field"),
                ],
                max_length=20,
            ),
        ),
    ]
