# Generated by Django 5.1.5 on 2025-02-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formbuilder", "0007_question_calculation_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="calculation_method",
            new_name="calculation_type",
        ),
    ]
